### ISSUE TITLE
ZooKeeper getData failed after 4 attempts

### ISSUE THREAD

**Issue by maximgeerinck** [actionml/analysis-tools#1]
Hello!
Thank you for this tool.

I keep getting the following error when running the tool

```
[ERROR] [RecoverableZooKeeper] ZooKeeper getData failed after 4 attempts
[ERROR] [ZooKeeperWatcher] hconnection-0x22167656, quorum=localhost:2181, baseZNode=/hbase Received unexpected KeeperException, re-throwing exception
```

and im using the following config

```
{
  "engine_config": "../engine.json",
  "splitting": {
    "version": "1",
    "source_file": "/data/exported/predictionio/",
    "train_file": "/data/exported/predictionio/train.json",
    "test_file": "/data/exported/predictionio/test.json",
    "type": "date",
    "train_ratio": 0.1,
    "random_seed": 29750,
    "split_event": "buy"
  },
  "reporting": {
    "file": "./report.xlsx",
    "csv_dir": "./report",
    "use_uuid": true
  },
  "testing": {
    "map_k": 10,
    "non_zero_users_file": "./non_zero_users.dat",
    "consider_non_zero_scores_only": true
  },
  "spark": {
    "master": "spark://127.0.0.1:7077"
  }
}
```

Is there anything i could do to fix this issue?

**Comment by pferrel** [comment]
We do not support those tools. They are too complicated to document and
support. Maybe someone on the list will know.

At first look, it appears PIO + UR are not running.


From: Maxim Geerinck <notifications@github.com> <notifications@github.com>
Reply: actionml/analysis-tools
<reply@reply.github.com>
<reply@reply.github.com>
Date: April 7, 2018 at 8:43:44 AM
To: actionml/analysis-tools <analysis-tools@noreply.github.com>
<analysis-tools@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  [actionml/analysis-tools] ZooKeeper getData failed after 4
attempts (#1)

Hello!
Thank you for this tool.

I keep getting the following error when running the tool

[ERROR] [RecoverableZooKeeper] ZooKeeper getData failed after 4 attempts
[ERROR] [ZooKeeperWatcher] hconnection-0x22167656,
quorum=localhost:2181, baseZNode=/hbase Received unexpected
KeeperException, re-throwing exception

and im using the following config

{
  "engine_config": "../engine.json",
  "splitting": {
    "version": "1",
    "source_file": "/data/exported/predictionio/",
    "train_file": "/data/exported/predictionio/train.json",
    "test_file": "/data/exported/predictionio/test.json",
    "type": "date",
    "train_ratio": 0.1,
    "random_seed": 29750,
    "split_event": "buy"
  },
  "reporting": {
    "file": "./report.xlsx",
    "csv_dir": "./report",
    "use_uuid": true
  },
  "testing": {
    "map_k": 10,
    "non_zero_users_file": "./non_zero_users.dat",
    "consider_non_zero_scores_only": true
  },
  "spark": {
    "master": "spark://127.0.0.1:7077"
  }
}

Is there anything i could do to fix this issue?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/actionml/analysis-tools/issues/1>, or mute the thread
